databases:
  - name: smart-queue-db
    plan: free
    databaseName: smartqueue
    user: smartqueue

services:
  - type: web
    name: smart-queue
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma db push && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: DATABASE_URL
        fromDatabase:
          name: smart-queue-db
          property: connectionString
